[project]
authors = ["novotny-marek <ahoj@mnovotny.xyz>"]
channels = ["conda-forge"]
name = "momeQ"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
qgis = ">=3.42.2,<4"
shapely = ">=2.1.1,<3"
geopandas = ">=1.0.1,<2"
numpy = ">=2.2.6,<3"
